return {
  highlight = { enable = true },
  indent = { enable = true },
  context_commentstring = { enable = true, enable_autocmd = false },
  ensure_installed = {
    "bash",
    "c",
    "css",
    "dockerfile",
    "eex",
    "elixir",
    "help",
    "html",
    "javascript",
    "json",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "scss",
    "sql",
    "swift",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
}
