return function()
  require("nvim-treesitter.configs").setup({
    highlight = { enable = true },
    indent = { enable = true },
    context_commentstring = { enable = true },
    auto_install = true,
    sync_install = false,
    ensure_installed = {
      "bash",
      "c",
      "css",
      "dockerfile",
      "eex",
      "elixir",
      "html",
      "javascript",
      "json",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "ruby",
      "rust",
      "scss",
      "sql",
      "swift",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "yaml",
    },
  })
end
