format="$all$custom$jobs$directory$character"
command_timeout=1000

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[aws]
symbol = " "

[c]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = "󰡨 "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[package]
symbol = " "

[php]
symbol =" "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[custom.os]
disabled = false
command = "os"
style = "bold white"
format = "[$symbol($output )]($style)"
symbol = ""
when = "true"
shell = ["bash", "--noprofile", "--norc"]

[git_branch]
format = "[$symbol$branch]($style) "

[directory]
style = "bold green"
