format="$all$custom$jobs$directory$character"

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[package]
symbol = " "

[ruby]
symbol = " "

[aws]
symbol = " "

[python]
symbol = " "

[elixir]
symbol = " "

[rust]
symbol = " "

[custom.os]
disabled = false
command = "os"
style = "bold white"
format = "[$symbol($output )]($style)"
symbol = ""
when = "true"
shell = ["bash", "--noprofile", "--norc"]

[git_branch]
format = "[$symbol$branch]($style) "

[directory]
style = "bold green"
